name = "yummy"
main = "worker.js"
compatibility_date = "2026-06-19"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bakery-shop-db"
database_id = "70e1d32e-8189-4520-9ccf-c047b68d8ac0"
